import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
part 'data_model.g.dart';

dynamic autoGeneratedFromJson(String str) => json.decode(str);

String autoGeneratedToJson(dynamic data) => json.encode(data);

@JsonSerializable(explicitToJson: true)
class DataModel {
  final int time;
  final String method;
  final String requestId;
  DataModel({required this.time, required this.method, required this.requestId});
  factory DataModel.fromJson(Map<String, dynamic> json) => _$DataModelFromJson(json);
  Map<String, dynamic> toJson() => _$DataModelToJson(this);
}

@JsonSerializable(explicitToJson: true)
class AutoGenerated {
  final int code;
  final String message;
  final DataModel data;
  AutoGenerated({required this.code, required this.message, required this.data});
  factory AutoGenerated.fromJson(Map<String, dynamic> json) => _$AutoGeneratedFromJson(json);
  Map<String, dynamic> toJson() => _$AutoGeneratedToJson(this);
}
