// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'data_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

DataModel _$DataModelFromJson(Map<String, dynamic> json) => DataModel(
  time: json['time'] as String,
  method: json['method'] as String,
  requestId: json['requestId'] as String,
);

Map<String, dynamic> _$DataModelToJson(DataModel instance) => <String, dynamic>{
  'time': instance.time,
  'method': instance.method,
  'requestId': instance.requestId,
};

AutoGenerated _$AutoGeneratedFromJson(Map<String, dynamic> json) => AutoGenerated(
  code: (json['code'] as num).toInt(),
  message: json['message'] as String,
  data: DataModel.fromJson(json['data'] as Map<String, dynamic>),
);

Map<String, dynamic> _$AutoGeneratedToJson(AutoGenerated instance) => <String, dynamic>{
  'code': instance.code,
  'message': instance.message,
  'data': instance.data.toJson(),
};
